// Mock data for PromptVault development

import { Prompt, Category } from '@/types';

export const categories: Category[] = [
    { id: '1', name: 'All', slug: 'all', icon: '✦' },
    { id: '2', name: 'Cinematic', slug: 'cinematic', icon: '🎬' },
    { id: '3', name: 'Portraits', slug: 'portraits', icon: '👤' },
    { id: '4', name: 'Sci-Fi', slug: 'sci-fi', icon: '🚀' },
    { id: '5', name: 'Fantasy', slug: 'fantasy', icon: '🔮' },
    { id: '6', name: 'Abstract', slug: 'abstract', icon: '◯' },
    { id: '7', name: 'Architecture', slug: 'architecture', icon: '🏛' },
    { id: '8', name: 'Nature', slug: 'nature', icon: '🌿' },
    { id: '9', name: 'Anime', slug: 'anime', icon: '✨' },
];

export const prompts: Prompt[] = [
    {
        id: '1',
        title: 'Neon Tokyo Nightscape',
        prompt_text: 'A cinematic wide shot of rain-soaked Tokyo streets at night, neon signs reflecting on wet asphalt, lone figure with umbrella walking away from camera, volumetric fog, cyberpunk atmosphere, Blade Runner inspired, 8k, photorealistic, dramatic lighting',
        image_url: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Cyberpunk',
        tags: ['cinematic', 'tokyo', 'neon', 'rain', 'night'],
        category: 'cinematic',
        created_at: '2024-01-15',
    },
    {
        id: '2',
        title: 'Ethereal Forest Spirit',
        prompt_text: 'Ancient forest spirit emerging from morning mist, bioluminescent mushrooms scattered around, ethereal glow, Studio Ghibli inspired, soft pastel colors, magical atmosphere, intricate details, 4k digital art',
        image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
        media_type: 'image',
        ai_model: 'DALL·E 3',
        style: 'Fantasy',
        tags: ['forest', 'spirit', 'magical', 'ghibli', 'ethereal'],
        category: 'fantasy',
        created_at: '2024-01-14',
    },
    {
        id: '3',
        title: 'Brutalist Cathedral',
        prompt_text: 'Massive brutalist concrete cathedral interior, dramatic god rays streaming through geometric windows, dust particles in light beams, symmetrical composition, architectural photography, Tadao Ando inspired',
        image_url: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Architectural',
        tags: ['brutalist', 'architecture', 'cathedral', 'concrete', 'dramatic'],
        category: 'architecture',
        created_at: '2024-01-13',
    },
    {
        id: '4',
        title: 'Cosmic Jellyfish',
        prompt_text: 'Giant translucent space jellyfish floating through nebula, bioluminescent tentacles trailing stardust, cosmic scale, deep space background with distant galaxies, ethereal beauty, trending on artstation',
        image_url: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&q=80',
        media_type: 'image',
        ai_model: 'Stable Diffusion XL',
        style: 'Surreal',
        tags: ['space', 'jellyfish', 'cosmic', 'nebula', 'surreal'],
        category: 'abstract',
        created_at: '2024-01-12',
    },
    {
        id: '5',
        title: 'Samurai in Cherry Blossoms',
        prompt_text: 'Lone samurai standing beneath ancient cherry blossom tree, petals falling in slow motion, morning mist, katana drawn, traditional armor with modern details, anime style, dramatic composition, soft pink lighting',
        image_url: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Anime',
        tags: ['samurai', 'cherry blossom', 'anime', 'japanese', 'warrior'],
        category: 'anime',
        created_at: '2024-01-11',
    },
    {
        id: '6',
        title: 'Desert Megastructure',
        prompt_text: 'Colossal abandoned megastructure in vast desert landscape, weathered metal and glass, sand dunes partially burying the base, tiny human figures for scale, golden hour lighting, Dune inspired, concept art',
        image_url: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
        media_type: 'image',
        ai_model: 'DALL·E 3',
        style: 'Sci-Fi',
        tags: ['desert', 'megastructure', 'scifi', 'abandoned', 'dune'],
        category: 'sci-fi',
        created_at: '2024-01-10',
    },
    {
        id: '7',
        title: 'Renaissance Cyborg',
        prompt_text: 'Renaissance portrait of a cyborg noblewoman, half mechanical face with intricate brass gears, oil painting style, chiaroscuro lighting, velvet clothing, Da Vinci meets cyberpunk, hyper detailed',
        image_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Portrait',
        tags: ['portrait', 'cyborg', 'renaissance', 'steampunk', 'detailed'],
        category: 'portraits',
        created_at: '2024-01-09',
    },
    {
        id: '8',
        title: 'Underwater Temple',
        prompt_text: 'Ancient Mayan temple submerged underwater, shafts of sunlight penetrating ocean surface, bioluminescent sea life, coral growing on stone columns, mysterious atmosphere, National Geographic style',
        image_url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
        media_type: 'image',
        ai_model: 'Stable Diffusion XL',
        style: 'Cinematic',
        tags: ['underwater', 'temple', 'ancient', 'ocean', 'mysterious'],
        category: 'cinematic',
        created_at: '2024-01-08',
    },
    {
        id: '9',
        title: 'Aurora Dreams',
        prompt_text: 'Northern lights dancing over frozen lake in Iceland, perfect mirror reflection, mountains silhouetted against aurora, long exposure photography style, vibrant greens and purples, ethereal landscape',
        image_url: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Landscape',
        tags: ['aurora', 'iceland', 'nature', 'night', 'landscape'],
        category: 'nature',
        created_at: '2024-01-07',
    },
    {
        id: '10',
        title: 'Floating Islands',
        prompt_text: 'Chain of floating islands connected by ancient rope bridges, waterfalls cascading into clouds below, lush vegetation, fantasy world, Studio Ghibli inspired, soft afternoon light, dreamy atmosphere',
        image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
        media_type: 'image',
        ai_model: 'DALL·E 3',
        style: 'Fantasy',
        tags: ['floating', 'islands', 'fantasy', 'ghibli', 'dreamy'],
        category: 'fantasy',
        created_at: '2024-01-06',
    },
    {
        id: '11',
        title: 'Geometric Void',
        prompt_text: 'Infinite geometric void with impossible architecture, Escher inspired, black and white with subtle gold accents, mathematical precision, recursive patterns, mind-bending perspective',
        image_url: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Abstract',
        tags: ['geometric', 'abstract', 'escher', 'patterns', 'void'],
        category: 'abstract',
        created_at: '2024-01-05',
    },
    {
        id: '12',
        title: 'Cybernetic Garden',
        prompt_text: 'Futuristic vertical garden with biomechanical plants, chrome and organic fusion, holographic flowers, neon irrigation systems, Singapore Gardens by the Bay meets Blade Runner, twilight scene',
        image_url: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&q=80',
        media_type: 'image',
        ai_model: 'Stable Diffusion XL',
        style: 'Sci-Fi',
        tags: ['garden', 'cyberpunk', 'futuristic', 'nature', 'neon'],
        category: 'sci-fi',
        created_at: '2024-01-04',
    },
    {
        id: '13',
        title: 'Storm Warrior',
        prompt_text: 'Weathered warrior standing on cliff edge during lightning storm, wind-swept cloak, glowing runic sword, dramatic backlighting, fantasy epic, dark and moody, cinematic composition',
        image_url: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Fantasy',
        tags: ['warrior', 'storm', 'fantasy', 'epic', 'dramatic'],
        category: 'fantasy',
        created_at: '2024-01-03',
    },
    {
        id: '14',
        title: 'Minimal Zen',
        prompt_text: 'Ultra minimal Japanese zen garden, single perfectly raked stone, morning dew, soft diffused light, negative space composition, wabi-sabi aesthetic, meditative atmosphere, 35mm photography',
        image_url: 'https://images.unsplash.com/photo-1580137189272-c9379f8864fd?w=800&q=80',
        media_type: 'image',
        ai_model: 'DALL·E 3',
        style: 'Minimal',
        tags: ['zen', 'minimal', 'japanese', 'garden', 'peaceful'],
        category: 'nature',
        created_at: '2024-01-02',
    },
    {
        id: '15',
        title: 'Android Portrait',
        prompt_text: 'Close-up portrait of android with human-like emotions, visible circuitry beneath translucent skin, single tear of liquid chrome, soft studio lighting, emotional depth, Blade Runner 2049 inspired',
        image_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Portrait',
        tags: ['android', 'portrait', 'scifi', 'emotional', 'futuristic'],
        category: 'portraits',
        created_at: '2024-01-01',
    },
    {
        id: '16',
        title: 'Mecha Sunrise',
        prompt_text: 'Giant mecha robot silhouette against blood orange sunrise, battle-damaged armor, standing in destroyed cityscape, smoke and debris, Evangelion inspired, anime style, dramatic scale',
        image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
        media_type: 'image',
        ai_model: 'Stable Diffusion XL',
        style: 'Anime',
        tags: ['mecha', 'anime', 'sunrise', 'robot', 'evangelion'],
        category: 'anime',
        created_at: '2023-12-31',
    },
    {
        id: '17',
        title: 'Glass Forest',
        prompt_text: 'Surreal forest where all trees are made of crystal glass, prismatic light refractions everywhere, rainbow caustics on forest floor, magical realism, hyper detailed, fantasy photography',
        image_url: 'https://images.unsplash.com/photo-1418065460487-3e41a6c84dc5?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Surreal',
        tags: ['glass', 'forest', 'crystal', 'surreal', 'magical'],
        category: 'abstract',
        created_at: '2023-12-30',
    },
    {
        id: '18',
        title: 'Noir Detective',
        prompt_text: 'Classic noir scene, detective in trench coat under streetlight, cigarette smoke curling, rain-slicked cobblestones, 1940s atmosphere, high contrast black and white, film grain, moody shadows',
        image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
        media_type: 'image',
        ai_model: 'DALL·E 3',
        style: 'Noir',
        tags: ['noir', 'detective', 'vintage', 'moody', 'cinematic'],
        category: 'cinematic',
        created_at: '2023-12-29',
    },
    {
        id: '19',
        title: 'Solarpunk City',
        prompt_text: 'Utopian solarpunk cityscape, buildings covered in vertical gardens, solar panels integrated into organic architecture, clean sky, happy diverse people, optimistic future, vibrant colors',
        image_url: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Sci-Fi',
        tags: ['solarpunk', 'city', 'utopia', 'green', 'future'],
        category: 'sci-fi',
        created_at: '2023-12-28',
    },
    {
        id: '20',
        title: 'Dragon Shrine',
        prompt_text: 'Ancient Asian mountain shrine with sleeping dragon coiled around pagoda, cherry blossoms falling, misty peaks in background, traditional ink painting meets photorealism, mythical atmosphere',
        image_url: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
        media_type: 'image',
        ai_model: 'Stable Diffusion XL',
        style: 'Fantasy',
        tags: ['dragon', 'shrine', 'asian', 'mountain', 'mythical'],
        category: 'fantasy',
        created_at: '2023-12-27',
    },
    {
        id: '21',
        title: 'Bioluminescent Cave',
        prompt_text: 'Underground cave system with bioluminescent organisms covering walls and ceiling, ethereal blue and green glow, crystal formations, underground lake with perfect reflection, Avatar inspired',
        image_url: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Fantasy',
        tags: ['cave', 'bioluminescent', 'underground', 'magical', 'avatar'],
        category: 'nature',
        created_at: '2023-12-26',
    },
    {
        id: '22',
        title: 'Retro Astronaut',
        prompt_text: 'Vintage 1960s astronaut portrait, worn NASA suit with mission patches, helmet visor reflecting Earth, film photography aesthetic, warm color grading, nostalgic space age feeling',
        image_url: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80',
        media_type: 'image',
        ai_model: 'DALL·E 3',
        style: 'Retro',
        tags: ['astronaut', 'retro', 'space', 'vintage', 'nasa'],
        category: 'portraits',
        created_at: '2023-12-25',
    },
    {
        id: '23',
        title: 'Fractal Cathedral',
        prompt_text: 'Infinite fractal cathedral interior, recursive Gothic arches extending forever, stained glass kaleidoscope patterns, mathematical beauty, DMT inspired visuals, transcendent atmosphere',
        image_url: 'https://images.unsplash.com/photo-1478860409698-8707f313ee8b?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Abstract',
        tags: ['fractal', 'cathedral', 'infinite', 'gothic', 'trippy'],
        category: 'abstract',
        created_at: '2023-12-24',
    },
    {
        id: '24',
        title: 'Witchcore Cottage',
        prompt_text: 'Cozy witchcore cottage interior, dried herbs hanging from ceiling, crystal collection, spell books, black cat on windowsill, autumn light streaming in, cottagecore meets witchy aesthetic',
        image_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80',
        media_type: 'image',
        ai_model: 'Stable Diffusion XL',
        style: 'Fantasy',
        tags: ['witch', 'cottage', 'cozy', 'autumn', 'magical'],
        category: 'fantasy',
        created_at: '2023-12-23',
    },
    {
        id: '25',
        title: 'Holographic Portrait',
        prompt_text: 'Glitched holographic portrait of woman, chromatic aberration effects, scan lines, digital noise, vaporwave colors, cyberpunk aesthetic, futuristic beauty, high fashion editorial',
        image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Portrait',
        tags: ['holographic', 'glitch', 'portrait', 'vaporwave', 'digital'],
        category: 'portraits',
        created_at: '2023-12-22',
    },
    {
        id: '26',
        title: 'Titan\'s Valley',
        prompt_text: 'Valley of sleeping stone titans, colossal ancient statues half-buried in landscape, miniature village built in titan\'s palm, morning mist, sense of incredible scale, fantasy world-building',
        image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
        media_type: 'image',
        ai_model: 'DALL·E 3',
        style: 'Fantasy',
        tags: ['titan', 'valley', 'giant', 'ancient', 'scale'],
        category: 'fantasy',
        created_at: '2023-12-21',
    },
    {
        id: '27',
        title: 'Cyberpunk Market',
        prompt_text: 'Bustling Asian night market in cyberpunk megacity, holographic vendor signs, noodle steam rising, diverse crowd, rain and neon reflections, Akira meets Ghost in the Shell, street level view',
        image_url: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Cyberpunk',
        tags: ['cyberpunk', 'market', 'neon', 'asian', 'night'],
        category: 'cinematic',
        created_at: '2023-12-20',
    },
    {
        id: '28',
        title: 'Spirit Fox',
        prompt_text: 'Kitsune spirit fox with nine tails, each tail a different ethereal color, traditional Japanese shrine background, cherry blossom petals, anime style with painterly touches, mystical atmosphere',
        image_url: 'https://images.unsplash.com/photo-1516934024742-b461fba47600?w=800&q=80',
        media_type: 'image',
        ai_model: 'Stable Diffusion XL',
        style: 'Anime',
        tags: ['kitsune', 'fox', 'anime', 'spirit', 'japanese'],
        category: 'anime',
        created_at: '2023-12-19',
    },
    {
        id: '29',
        title: 'Monolithic Gateway',
        prompt_text: 'Mysterious monolithic gateway standing alone in empty desert, perfect black rectangle, 2001 Space Odyssey inspired, stark minimalism, human figure approaching for scale, otherworldly presence',
        image_url: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80',
        media_type: 'image',
        ai_model: 'Midjourney v6',
        style: 'Minimal',
        tags: ['monolith', 'gateway', 'desert', 'mysterious', 'minimal'],
        category: 'abstract',
        created_at: '2023-12-18',
    },
    {
        id: '30',
        title: 'Ocean Wanderer',
        prompt_text: 'Massive steampunk ship sailing through clouds above endless ocean, Victorian era design with brass and copper, billowing steam, adventure awaits, detailed illustration, warm sunset colors',
        image_url: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800&q=80',
        media_type: 'image',
        ai_model: 'DALL·E 3',
        style: 'Steampunk',
        tags: ['steampunk', 'ship', 'clouds', 'ocean', 'adventure'],
        category: 'sci-fi',
        created_at: '2023-12-17',
    },
];
